// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentEnrollmentSystem.Infrastructure.Persistence;

namespace StudentEnrollmentSystem.Infrastructure.Migrations
{
    [DbContext(typeof(StudentEnrollmentSystemDbContext))]
    partial class StudentEnrollmentSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StudentEnrollmentSystem.Domain.Entities.EnrollmentDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("enrollmentSemester")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("enrollmentYear")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("EnrollmentDetails");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Domain.Entities.StudentBasicInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StudentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentAge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentEmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentMiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("StudentBasicInfos");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Domain.Entities.StudentProfessor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProfName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentSubjectsID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("StudentProfessors");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Domain.Entities.StudentSubjectList", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EnrollmentDetailsID")
                        .HasColumnType("int");

                    b.Property<int>("StudentBasicInfoID")
                        .HasColumnType("int");

                    b.Property<int>("StudentProfessorID")
                        .HasColumnType("int");

                    b.Property<int>("StudentSubjectsID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("StudentSubjectLists");
                });

            modelBuilder.Entity("StudentEnrollmentSystem.Domain.Entities.StudentSubjects", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("StudentSubjects");
                });
#pragma warning restore 612, 618
        }
    }
}
